sonar.projectKey=Mahery23_tp2-auth
sonar.organization=mahery23
sonar.projectName=tp2-auth
sonar.projectVersion=1.0
sonar.sources=tp2-auth/src/main/java
sonar.tests=tp2-auth/src/test/java
sonar.java.binaries=tp2-auth/target/classes
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=tp2-auth/target/site/jacoco/jacoco.xml