sonar.projectKey=Mahery23_tp2-auth
sonar.organization=mahery23

sonar.projectName=tp2-auth
sonar.projectVersion=1.0

sonar.sources=./src
sonar.java.binaries=./bin/com/example/sonarplayground

sonar.language=java
sonar.sourceEncoding=UTF-8
